// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJa49jOwZ7BAtMs4_qnnBICroc5pB7vV4',
    appId: '1:23193144651:web:abb5bac5b2db8625546cce',
    messagingSenderId: '23193144651',
    projectId: 'chatboard-172bf',
    authDomain: 'chatboard-172bf.firebaseapp.com',
    storageBucket: 'chatboard-172bf.firebasestorage.app',
    measurementId: 'G-WN3D5QD9GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRP69o9RT7P_o3ovC0Ow9BP3IJ2YFIF4',
    appId: '1:23193144651:android:47971b3567c538fa546cce',
    messagingSenderId: '23193144651',
    projectId: 'chatboard-172bf',
    storageBucket: 'chatboard-172bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVg1lldR62K7hA3LhvZ39rheXBqW8NU8k',
    appId: '1:23193144651:ios:2c3aa553d5749aae546cce',
    messagingSenderId: '23193144651',
    projectId: 'chatboard-172bf',
    storageBucket: 'chatboard-172bf.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVg1lldR62K7hA3LhvZ39rheXBqW8NU8k',
    appId: '1:23193144651:ios:2c3aa553d5749aae546cce',
    messagingSenderId: '23193144651',
    projectId: 'chatboard-172bf',
    storageBucket: 'chatboard-172bf.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJa49jOwZ7BAtMs4_qnnBICroc5pB7vV4',
    appId: '1:23193144651:web:4ac41820338aa1a7546cce',
    messagingSenderId: '23193144651',
    projectId: 'chatboard-172bf',
    authDomain: 'chatboard-172bf.firebaseapp.com',
    storageBucket: 'chatboard-172bf.firebasestorage.app',
    measurementId: 'G-Q69J0FG168',
  );
}
